# Generated by Django 3.0.6 on 2020-05-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_confirmorder_payment_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quanity',
            field=models.IntegerField(default=0),
        ),
    ]
